apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crm
  namespace: openshift-gitops
spec:
  description: "GitOps AppProject for CRM tenant"
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'crm'
      server: 'https://kubernetes.default.svc'
    - namespace: 'crm-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

