apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-serverless.redhat-operators: ""
  name: serverless-operator
  namespace: openshift-serverless
  annotations:
      argocd.argoproj.io/sync-wave: "3"
spec:
  channel: stable
  installPlanApproval: Manual
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: serverless-operator.v1.34.1
