---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-gpu-console-plugin
  namespace: nvidia-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-gpu-console-plugin
rules:
  - apiGroups:
      - operator.openshift.io
    resources:
      - consoles
    verbs:
      - get
      - list
      - patch
      - label
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-gpu-console-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-gpu-console-plugin
subjects:
  - kind: ServiceAccount
    name: job-gpu-console-plugin
    namespace: nvidia-gpu-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-gpu-console-plugin
  namespace: nvidia-gpu-operator
  generateName: job-gpu-console-plugin-
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          env:
            - name: PLUGIN_NAME
              value: console-plugin-nvidia-gpu
          command:
            - /bin/bash
            - -c
            - |
              enable_console_plugin(){
                [ -z "${PLUGIN_NAME}" ] && return 1
              
                echo "Attempting to enable ${PLUGIN_NAME} plugin"
                echo ""
              
                # Create the plugins section on the object if it doesn't exist
                if [ -z "$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')" ]; then
                  echo "Creating plugins object"
                  oc patch consoles.operator.openshift.io cluster --patch '{ "spec": { "plugins": [] } }' --type=merge
                fi
              
                INSTALLED_PLUGINS=$(oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}')
                echo "Current plugins:"
                echo "${INSTALLED_PLUGINS}"
              
                if [[ "${INSTALLED_PLUGINS}" == *"${PLUGIN_NAME}"* ]]; then
                    echo "${PLUGIN_NAME} is already enabled"
                else
                    echo "Enabling plugin: ${PLUGIN_NAME}"
                    oc patch consoles.operator.openshift.io cluster --type=json --patch '[{"op": "add", "path": "/spec/plugins/-", "value": "'"${PLUGIN_NAME}"'"}]'
                fi
              
                sleep 6
                oc get consoles.operator.openshift.io cluster -o=jsonpath='{.spec.plugins}'
              }
              
              enable_console_plugin
      restartPolicy: Never
      serviceAccount: job-gpu-console-plugin
      serviceAccountName: job-gpu-console-plugin
  backoffLimit: 4